version: 2.1

jobs:
  build:
    parameters:
      docker-image:
        type: string
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - run: ruby --version
      - when:
          condition:
            equal: [ "ruby:1.9", << parameters.docker-image >>]
          steps:
            - run: gem update --system 2.7.8
            - run: gem install bundler -v1.17.3
      - when:
          condition:
            equal: [ "jruby:latest", << parameters.docker-image >>]
          steps:
            - run: apt-get update
            - run: apt-get install -y git
      - run: gem --version
      - run: bundle --version
      - run: bundle install
      - run: bundle exec rake

workflows:
  build-all:
    jobs: &all-jobs
      - build:
          matrix:
            parameters:
              docker-image:
                - ruby:2.1
                - ruby:2.2
                - ruby:2.3
                - ruby:2.4
                - ruby:2.5
                - ruby:2.6
                - ruby:2.7
                - ruby:latest
                - jruby:latest
  weekly:
    triggers:
      - schedule:
          cron: "0 2 * * 0"
          filters:
            branches:
              only:
                - main
    jobs: *all-jobs
